version: "3"
services:
    # ... other services ...

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"

        volumes:
            - .:/app
            - /app/node_modules
