import Providers from "@/library/providers/MainProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Demis Rincon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
