import Providers from "@/library/providers/MainProvider";
import type { Metadata } from "next";
import Header from "./@header/page";
import Foother from "./@foother/page";

export const metadata: Metadata = {
  title: "Portfolio Demis Rincon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Foother />
        </Providers>
      </body>
    </html>
  );
}
